/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */

use std::cell::Cell;

use app_units::Au;
use malloc_size_of_derive::MallocSizeOf;
use paint_api::display_list::AxesScrollSensitivity;
use servo_base::print_tree::PrintTree;
use style::Zero;
use style::computed_values::position::T as Position;
use style::selector_parser::PseudoElement;

use super::{BoxFragment, ContainingBlockManager, Fragment, SpecificLayoutInfo};
use crate::ArcRefCell;
use crate::geom::{PhysicalPoint, PhysicalRect, PhysicalSize};

#[derive(MallocSizeOf)]
pub struct FragmentTree {
    /// Fragments at the top-level of the tree.
    ///
    /// If the root element has `display: none`, there are zero fragments.
    /// Otherwise, there is at least one:
    ///
    /// * The first fragment is generated by the root element.
    /// * There may be additional fragments generated by positioned boxes
    ///   that have the initial containing block.
    pub(crate) root_fragments: Vec<Fragment>,

    /// The scrollable overflow rectangle for the entire tree
    /// <https://drafts.csswg.org/css-overflow/#scrollable>
    scrollable_overflow: Cell<Option<PhysicalRect<Au>>>,

    /// The containing block used in the layout of this fragment tree.
    pub(crate) initial_containing_block: PhysicalRect<Au>,

    /// Whether or not the viewport is sensitive to scroll input events.
    pub viewport_scroll_sensitivity: AxesScrollSensitivity,
}

impl FragmentTree {
    pub(crate) fn new(
        mut root_fragments: Vec<Fragment>,
        initial_containing_block: PhysicalRect<Au>,
        viewport_scroll_sensitivity: AxesScrollSensitivity,
    ) -> Self {
        position_range_input_shadow_trees(&mut root_fragments);

        let fragment_tree = Self {
            root_fragments,
            scrollable_overflow: Cell::default(),
            initial_containing_block,
            viewport_scroll_sensitivity,
        };

        fragment_tree.find(|fragment, _level, containing_block| {
            fragment.set_containing_block(containing_block);
            None::<()>
        });

        fragment_tree
    }

    pub fn print(&self) {
        let mut print_tree = PrintTree::new("Fragment Tree".to_string());
        for fragment in &self.root_fragments {
            fragment.print(&mut print_tree);
        }
    }

    pub(crate) fn scrollable_overflow(&self) -> PhysicalRect<Au> {
        self.scrollable_overflow
            .get()
            .expect("Should only call `scrollable_overflow()` after calculating overflow")
    }

    /// Calculate the scrollable overflow / scrolling area for this [`FragmentTree`] according
    /// to <https://drafts.csswg.org/cssom-view/#scrolling-area>.
    pub(crate) fn calculate_scrollable_overflow(&self) {
        let scrollable_overflow = || {
            let Some(first_root_fragment) = self.root_fragments.first() else {
                return self.initial_containing_block;
            };

            let scrollable_overflow = self.root_fragments.iter().fold(
                self.initial_containing_block,
                |overflow, fragment| {
                    // Need to calculate the overflow for each fragments within the tree
                    // because it is required in the next stages of reflow.
                    let overflow_from_fragment =
                        fragment.calculate_scrollable_overflow_for_parent();

                    // Scrollable overflow should be accumulated in the block that
                    // establishes the containing block for the element. Thus, fixed
                    // positioned fragments whose containing block is the initial
                    // containing block should not be included in overflow calculation.
                    // See <https://www.w3.org/TR/css-overflow-3/#scrollable>.
                    if fragment
                        .retrieve_box_fragment()
                        .is_some_and(|box_fragment| {
                            box_fragment.borrow().style().get_box().position == Position::Fixed
                        })
                    {
                        return overflow;
                    }

                    overflow.union(&overflow_from_fragment)
                },
            );

            // Assuming that the first fragment is the root element, ensure that
            // scrollable overflow that is unreachable is not included in the final
            // rectangle. See
            // <https://drafts.csswg.org/css-overflow/#scrolling-direction>.
            let first_root_fragment = match first_root_fragment {
                Fragment::Box(fragment) | Fragment::Float(fragment) => fragment.borrow(),
                _ => return scrollable_overflow,
            };
            if !first_root_fragment.is_root_element() {
                return scrollable_overflow;
            }
            first_root_fragment.clip_wholly_unreachable_scrollable_overflow(
                scrollable_overflow,
                self.initial_containing_block,
            )
        };

        self.scrollable_overflow.set(Some(scrollable_overflow()))
    }

    pub(crate) fn find<T>(
        &self,
        mut process_func: impl FnMut(&Fragment, usize, &PhysicalRect<Au>) -> Option<T>,
    ) -> Option<T> {
        let info = ContainingBlockManager {
            for_non_absolute_descendants: &self.initial_containing_block,
            for_absolute_descendants: None,
            for_absolute_and_fixed_descendants: &self.initial_containing_block,
        };
        self.root_fragments
            .iter()
            .find_map(|child| child.find(&info, 0, &mut process_func))
    }

    /// Find the `<body>` element's [`Fragment`], if it exists in this [`FragmentTree`].
    pub(crate) fn body_fragment(&self) -> Option<ArcRefCell<BoxFragment>> {
        fn find_body(children: &[Fragment]) -> Option<ArcRefCell<BoxFragment>> {
            children.iter().find_map(|fragment| {
                match fragment {
                    Fragment::Box(box_fragment) | Fragment::Float(box_fragment) => {
                        let borrowed_box_fragment = box_fragment.borrow();
                        if borrowed_box_fragment.is_body_element_of_html_element_root() {
                            return Some(box_fragment.clone());
                        }

                        // The fragment for the `<body>` element is typically a child of the root (though,
                        // not if it's absolutely positioned), so we need to recurse into the children of
                        // the root to find it.
                        //
                        // Additionally, recurse into any anonymous fragments, as the `<body>` fragment may
                        // have created anonymous parents (for instance by creating an inline formatting context).
                        if borrowed_box_fragment.is_root_element() ||
                            borrowed_box_fragment.base.is_anonymous()
                        {
                            find_body(&borrowed_box_fragment.children)
                        } else {
                            None
                        }
                    },
                    Fragment::Positioning(positioning_context)
                        if positioning_context.borrow().base.is_anonymous() =>
                    {
                        // If the `<body>` element is a `display: inline` then it might be nested inside of a
                        // `PositioningFragment` for the purposes of putting it on the first line of the implied
                        // inline formatting context.
                        find_body(&positioning_context.borrow().children)
                    },
                    _ => None,
                }
            })
        }

        find_body(&self.root_fragments)
    }
}

fn position_range_input_shadow_trees(fragments: &mut [Fragment]) {
    for fragment in fragments {
        let Some(box_fragment) = fragment.retrieve_box_fragment() else {
            continue;
        };

        {
            let mut fragment = box_fragment.borrow_mut();
            let range_value_fraction =
                fragment
                    .specific_layout_info()
                    .as_deref()
                    .and_then(|info| match info {
                        SpecificLayoutInfo::RangeInput { value_fraction } => Some(*value_fraction),
                        _ => None,
                    });
            if let Some(value_fraction) = range_value_fraction {
                position_range_input_shadow_tree(&mut fragment, value_fraction);
            }
            position_range_input_shadow_trees(&mut fragment.children);
        }
    }
}

fn position_range_input_shadow_tree(range: &mut BoxFragment, value_fraction: f32) {
    let content_size = range.content_rect().size;
    let writing_mode = range.style().writing_mode;
    let is_horizontal = writing_mode.is_horizontal();
    let is_reversed = if is_horizontal {
        !writing_mode.is_bidi_ltr()
    } else {
        !writing_mode.is_inline_tb()
    };
    let fraction = if is_reversed {
        1.0 - value_fraction
    } else {
        value_fraction
    };

    let thumb_size = range
        .children
        .iter()
        .find(|child| has_pseudo(child, PseudoElement::SliderThumb))
        .and_then(|child| child.retrieve_box_fragment())
        .map(|thumb| thumb.borrow().border_rect().size)
        .unwrap_or_default();

    for child in &range.children {
        if has_pseudo(child, PseudoElement::SliderTrack) {
            if let Some(track) = child.retrieve_box_fragment() {
                let mut track = track.borrow_mut();
                let track_size = track.border_rect().size;
                let origin = if is_horizontal {
                    PhysicalPoint::new(
                        Au::zero(),
                        (content_size.height - track_size.height).scale_by(0.5),
                    )
                } else {
                    PhysicalPoint::new(
                        (content_size.width - track_size.width).scale_by(0.5),
                        Au::zero(),
                    )
                };
                set_border_box_origin(&mut track, origin);
                position_range_fill(
                    &mut track,
                    content_size,
                    thumb_size,
                    fraction,
                    is_horizontal,
                );
            }
        } else if has_pseudo(child, PseudoElement::SliderThumb) {
            if let Some(thumb) = child.retrieve_box_fragment() {
                let mut thumb = thumb.borrow_mut();
                let traversable = if is_horizontal {
                    content_size.width - thumb_size.width
                } else {
                    content_size.height - thumb_size.height
                };
                let progress = traversable.scale_by(fraction);
                let origin = if is_horizontal {
                    PhysicalPoint::new(
                        progress,
                        (content_size.height - thumb_size.height).scale_by(0.5),
                    )
                } else {
                    PhysicalPoint::new(
                        (content_size.width - thumb_size.width).scale_by(0.5),
                        progress,
                    )
                };
                set_border_box_origin(&mut thumb, origin);
            }
        }
    }
}

fn position_range_fill(
    track: &mut BoxFragment,
    range_size: PhysicalSize<Au>,
    thumb_size: PhysicalSize<Au>,
    fraction: f32,
    is_horizontal: bool,
) {
    for child in &track.children {
        if !has_pseudo(child, PseudoElement::SliderFill) {
            continue;
        }
        let Some(fill) = child.retrieve_box_fragment() else {
            continue;
        };
        let mut fill = fill.borrow_mut();
        let fill_size = fill.border_rect().size;
        if is_horizontal {
            let traversable = range_size.width - thumb_size.width;
            let width = traversable.scale_by(fraction) + thumb_size.width.scale_by(0.5);
            set_border_box_size(&mut fill, PhysicalSize::new(width, fill_size.height));
            set_border_box_origin(&mut fill, PhysicalPoint::new(Au::zero(), Au::zero()));
        } else {
            let traversable = range_size.height - thumb_size.height;
            let height = traversable.scale_by(fraction) + thumb_size.height.scale_by(0.5);
            set_border_box_size(&mut fill, PhysicalSize::new(fill_size.width, height));
            set_border_box_origin(&mut fill, PhysicalPoint::new(Au::zero(), Au::zero()));
        }
    }
}

fn has_pseudo(fragment: &Fragment, pseudo: PseudoElement) -> bool {
    fragment
        .tag()
        .is_some_and(|tag| tag.pseudo_element_chain.innermost() == Some(pseudo))
}

fn set_border_box_origin(fragment: &mut BoxFragment, origin: PhysicalPoint<Au>) {
    fragment.base.rect.origin = PhysicalPoint::new(
        origin.x + fragment.border.left + fragment.padding.left,
        origin.y + fragment.border.top + fragment.padding.top,
    );
}

fn set_border_box_size(fragment: &mut BoxFragment, size: PhysicalSize<Au>) {
    fragment.base.rect.size = PhysicalSize::new(
        Au::zero().max(
            size.width
                - fragment.border.left
                - fragment.border.right
                - fragment.padding.left
                - fragment.padding.right,
        ),
        Au::zero().max(
            size.height
                - fragment.border.top
                - fragment.border.bottom
                - fragment.padding.top
                - fragment.padding.bottom,
        ),
    );
}
